const SONGS = {
    1: "Baby Rasta y Gringo - Me Niegas (Official Video)-xfHZOY03y2w",
    2: "Akon",
    3: "BAD BUNNY - NI BIEN NI MAL _ X100PRE (Video Oficial)-4oiZdbwxUuQ",
    4: "BAD BUNNY - SOY PEOR (Video Oficial)-ws00k_lIQ9U",
    5: "BAD BUNNY - VETE _ YHLQMDLG (Video Oficial)-f5aDUB1NCnk",
    6: "Bandoleros-7dDmJzNC1sg",
    7: "Calle 13 - Atrevete te te (Explicit)-vXtJkDHEAAc",
    8: "Chino & Nacho - Me Voy Enamorando ft. Farruko (Remix) (Official Music Video)-0yr75-gxVtM",
    9: "Daddy Yankee - La Nueva y La Ex-A13QPvFWqvo",
    10: "Daddy Yankee - Limbo (Video Oficial)-6BTjG-dhf5s",
    11: "Daddy Yankee 'Llamado De Emergencia' Soundtrack Talento de Barrio © El Cartel Records-ekFaaEU8Yuw",
    12: "Dalmata - Pasarela _ Video Oficial-spt1zvbezyE",
    13: "Don Omar - Angelito (Official Music Video)-8einbrSxt0M",
    14: "Don Omar - Ayer La Vi (Lyric Video)-dv518KcbSfM",
    15: "Don Omar - Hasta Abajo-SMM1WhmlQzI",
    16: "Don Omar - Ojitos Chiquitos (Lyric Video)-yYMEMTZp2QA",
    17: "Don Omar - Ojitos Chiquitos-lY7G2FSSmnQ",
    18: "Don Omar - Salio El Sol (Official Music Video)-Z-3su2ov8Vg",
    19: "Don Omar - Taboo-lRWqYR3e7xE",
    20: "Don Omar - Virtual Diva-vRBgZ4aMPio",
    21: "Don Omar ft. Plan B - Hooka (Lyric Video)-L4tCfUbicfo",
    22: "Don Omar ft. Tego Calderon - Bandolero-_i2EwTKRmsU",
    23: "Dr. Dre - Forgot About Dre ft. Eminem, Hittman-E5a93wABHNM",
    24: "Dr. Dre ft. Eminem, Skylar Grey - I Need A Doctor (Explicit) [Official Video]-VA770wpLX-Q",
    25: "Ella Es La Sensacion Del Bloque-AFrG8gS9748",
    26: "Ella Y Yo (Feat. Don Omar)-JPYtPUfV9BU",
    27: "Eminem - Beautiful (Official Music Video)-lgT1AidzRWM",
    28: "Eminem - Cleanin' Out My Closet (Official Music Video)-RQ9_TKayu9s",
    29 : "Eminem - Guilty Conscience (Official Music Video) ft. Dr. Dre-Xbw_BxDwdjk",
    30: "Eminem - Just Lose It (Official Music Video)-9dcVOmEQzKA",
    31: "Eminem - Like Toy Soldiers (Official Music Video)-lexLAjh8fPA",
    32: "Eminem - Lose Yourself (set to clips from 8 Mile)-z_FzrqxfZ9U",
    33: "Eminem - Love The Way You Lie ft. Rihanna-uelHwf8o7_U",
    34: "Eminem - Mockingbird (Official Music Video)-S9bCLPwzSC0",
    35: "Eminem - My Name Is (Official Music Video)-sNPnbI1arSE",
    36: "Eminem - Not Afraid (Official Video)-j5-yKhDd64s",
    37: "Eminem - Sing For The Moment (Official Music Video)-D4hAVemuQXY",
    38: "Eminem - Stan (Long Version) ft. Dido-gOMhN-hfMtY",
    38: "Eminem - Superman (Clean Version)-8kYkciD9VjU",
    39: "eminem - superman-_WYO5EGTY-o",
    40: "Eminem - The Real Slim Shady (Official Video - Clean Version)-eJO5HU_7_1w",
    41: "Eminem - The Warning (Mariah Carey Diss)-kzHnNPLWsDQ",
    42: "Eminem - We Made You (Official Music Video)-RSdKmX2BH7o",
    43: "Eminem - When I'm Gone (Official Music Video)-1wYNFfgrXTI",
    44: "Eminem - White America (Official Music Video)-RZIzD0ZfTFg",
    45: "Eminem - Without Me (Official Music Video)-YVkUvmDQ3HY",
    46: "Eminem - You Don't Know (Official Music Video) ft. 50 Cent, Cashis, Lloyd Banks-ngH0fkiNo-g",
    47: "Eminem & Tupac - When I'm Gone (Remix)-X7gVu9JuqUk",
    48: "Jhay Cortez, J. Balvin, Bad Bunny - No Me Conoce (Remix)-w2C6RhQBYlg",
    49: "La Diabla-aQO2nek3bUY",
    50: "Lil Wayne - Drop The World ft. Eminem (Official Music Video) ft. Eminem-ErCAOMi5EGM",
    51: "Llegamos A La Disco-t70NEAfN0oI",
    52: "Los 10 Clasicos De Reggaeton Que Marcaron Tu Infancia-PTMo7LI0zes",

}